import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { sharedOf } from './stack.mjs';

// MUNNI_RENDER_DIR: test override so specs never touch a real rendered/
const OUT_DIR = () => process.env.MUNNI_RENDER_DIR ?? join(dirname(fileURLToPath(import.meta.url)), '..', 'rendered');

/**
 * The stack's runbook, rendered with the actual values: what the setup
 * did by itself, the few things that stay manual, and where everything
 * lives. Steady-state deploys need none of it.
 */
export function renderRunbook(stack, { minted = [], missingOperator = [] } = {}) {
  const dir = join(OUT_DIR(), stack.stack);
  mkdirSync(dir, { recursive: true });
  const file = join(dir, `runbook.${stack.stack}.md`);
  const shared = sharedOf(stack);
  const nas = stack.delivery === 'synology';
  const links = stack.role === 'shared'
    ? `- crash reports ${stack.urls.glitchtip} · vault ${stack.urls.vault} · control ${stack.urls.control} · pgAdmin ${stack.urls.pgadmin}`
    : `- app ${stack.urls.web} · admin ${stack.urls.admin} · api ${stack.urls.api}/health\n- sign-in ${stack.urls.logto} · Logto console ${stack.urls.logtoAdmin}\n- crash reports (shared) ${shared.urls.glitchtip} · vault (shared) ${shared.urls.vault}`;
  const rules = Object.keys(stack.hosts).map((k) => `- ${stack.host(k)} → localhost:${stack.ports[k]}`).join('\n');
  writeFileSync(file, `# Runbook — ${stack.stack} (${stack.platformLabel}, ${stack.role === 'shared' ? 'shared services' : `environment "${stack.env}"`})

Generated by \`bootstrap --stack ${stack.stack}\`. Secrets minted this run: ${minted.length ? minted.join(', ') : 'none'}.
${missingOperator.length ? `\n> ⚠ Operator values still missing: ${missingOperator.join(', ')} — the wizard's tiles store them.\n` : ''}
## Where it lives

${links}
${nas ? `
GitHub environment \`${stack.githubEnvironment}\` holds its secrets; the
bundle lands in \`${stack.publishedPath}\` and the poller (Task Scheduler
"munni deploy poller") composes it up in \`/volume1${stack.publishedPath.replace(/\/published$/, '')}/${stack.stack}/\`.

## Done by the setup

- Reverse-proxy rules (DSM Application Portal), bound to the platform's wildcard certificate:
${rules}
${stack.role === 'shared' ? '- The wildcard certificate (Let\'s Encrypt through DSM), the live dir and the poller task.\n- GlitchTip\'s admin + API token (created inside the container on deploy); the vault account.' : '- Logto: apps, API resource with the `admin` scope, the `munni admin` role, social connectors, branding, the console\'s admin (created on deploy from the seeded machine credentials).\n- GlitchTip projects + DSNs, written back to the environment.\n- Every minted credential in the platform\'s vault, folder `' + stack.stack + '`.'}

## Still manual (once per platform)

- DNS: the *.<domain> wildcard of Synology DDNS covers every host; an own registrar needs the records.
- DSM firewall: allow 172.16.0.0/12 (docker) so Logto reaches its own console endpoint through the host, and LAN-restrict the admin, console, vault, control and pgAdmin hosts.
- The deploy account: a DSM administrator with DSM + File Station allowed and 2FA off (the wizard's Synology tile checks it).
` : `
The helper renders \`.env.${stack.stack}\` with real values from the local stores
(\`infra/rendered/\`, gitignored) and runs \`docker compose --env-file .env.${stack.stack} -f docker-compose.${stack.stack}.yml up -d\` here.

## Done by the setup

${stack.role === 'shared' ? '- GlitchTip admin + API token, the vault account, pgAdmin, the family Caddy (https for every hostname in LAN mode).' : '- Logto: apps, API resource with the `admin` scope, the `munni admin` role, social connectors, branding, the console\'s admin.\n- GlitchTip projects + DSNs.\n- Every minted credential in the platform\'s vault, folder `' + stack.stack + '`.'}
`}
## Native apps

Store records cannot be created by API: the wizard's Phones tab names the
package (\`${stack.native?.appId ?? '—'}\`) and walks through the one-time Play
Console / App Store Connect steps; every later build publishes itself.

## Verify

\`node infra/bootstrap.mjs --stack ${stack.stack} --verify\`
`);
  return file;
}
